# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

INT_MAX = 4000000

def fib(n):
	if n == 0:
		return 1
	elif n == 1:
		return 2
	else:
		return fib(n - 1) + fib(n - 2)

def main():
	list = [fib(n) for n in range(40) if fib(n) % 2 == 0 and fib(n) <= INT_MAX]
	print(list)
	total = sum(list)
	print(total)

if __name__ == '__main__':
	main()